### ISSUE TITLE
Add .gitignore 

### ISSUE THREAD

**Issue by aweinert-MIT** [nrc-cnrc/Canadian-Airspace-Models#10]
To improve robustness of use of this repository, please add a `.gitignore` file. GitHub provides a collection of templates here: https://github.com/github/gitignore.

**Comment by ftessier** [comment]
This may prove a useful starting point for a MATLAB repo:

https://github.com/github/gitignore/blob/main/Global/MATLAB.gitignore

**Comment by spydoctor** [comment]
Added Matlab gitignore file, as suggested!

**Comment by ftessier** [comment]
Oh, I don't think git will consider the file `MATLAB.gitignore`, as far as I know it just looks at `.gitignore`. The provided files shows what to put in `.gitignore` to disregard common MATLAB binaries etc. Here you can simply move `MATLAB.gitignore` to `.gitignore`, since there was no previous `.gitignore`.

**Comment by spydoctor** [comment]
@ftessier Corrected!

**Comment by aweinert-MIT** [comment]
> Oh, I don't think git will consider the file `MATLAB.gitignore`, as far as I know it just looks at `.gitignore`. The provided files shows what to put in `.gitignore` to disregard common MATLAB binaries etc. Here you can simply move `MATLAB.gitignore` to `.gitignore`, since there was no previous `.gitignore`.

Correct.

**Comment by spydoctor** [comment]
@ftessier I moved content of Matlab.gitignore to .gitignore, on your advise.
I can now close the issue, if it looks good :)

**Comment by aweinert-MIT** [comment]
> @ftessier I moved content of Matlab.gitignore to .gitignore, on your advise. I can now close the issue, if it looks good :)

A quick review of the main branch looks good with the `.gitignore`

**Comment by spydoctor** [comment]
@aweinert-MIT Thanks Andrew! I will now close this issue. Please let me know if you have any other suggestions, and thanks for the star ;)

**Comment by aweinert-MIT** [comment]
> @aweinert-MIT Thanks Andrew! I will now close this issue. Please let me know if you have any other suggestions, and thanks for the star ;)

Already created pull request #21 to help with repo admin 😄

**Comment by spydoctor** [comment]
@aweinert-MIT And approved 😄
