### ISSUE TITLE
Issue persistent DOI

### ISSUE THREAD

**Issue by aweinert-MIT** [nrc-cnrc/Canadian-Airspace-Models#8]
Documentation: https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content

Recommend [issuing a persistent identifier for this repository with Zenodo](https://docs.github.com/en/repositories/archiving-a-github-repository/referencing-and-citing-content#issuing-a-persistent-identifier-for-your-repository-with-zenodo) to enable easy and robust citations in peer-review article articles and ASTM / RTCA standards.

**Comment by ftessier** [comment]
@spydoctor You can also ask NRC to generate a DOI, but in that case it will have to link to an NRC page, which can link to the repo on github. Zenodo is convenient, however the doi links to a zipped released version of your code stored on https://zenodo.org/ instead of the repository itself.

**Comment by spydoctor** [comment]
Thanks. DOI was created using Zenodo. It is 10.5281/zenodo.8118133

**Comment by spydoctor** [comment]
DOI created using Zenodo

**Comment by ftessier** [comment]
Nice, you can copy the "badge" image from Zenodo to your readme if you want, as a quick way to show your doi.

**Comment by ftessier** [comment]
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.8118133.svg)](https://doi.org/10.5281/zenodo.8118133)

**Comment by ftessier** [comment]
Strange: on the Zenodo page it says that licence is Creative Commons. I assumed that it would pick up the MIT LICENCE automatically!?

![image](https://github.com/nrc-cnrc/Canadian-Airspace-Models/assets/1444241/1770faf6-dacc-41cf-b3f5-e08914810028)

**Comment by spydoctor** [comment]
Indeed, very strange...

**Comment by ftessier** [comment]
Is there any way to edit the record? I mean the `LICENCE` file is included in the zip, so this is just misleading people looking at the Zenodo page; the MIT licence is still in effect.

**Comment by spydoctor** [comment]
I just manually corrected :) It worked!

**Comment by ftessier** [comment]
Note that there is a useful stable "base" doi https://doi.org/10.5281/zenodo.8118132 which always points to the latest version of your software:

![image](https://github.com/nrc-cnrc/Canadian-Airspace-Models/assets/1444241/5ee12667-1628-4931-99dd-e068b108355b)

**Comment by aweinert-MIT** [comment]
> Note that there is a useful stable "base" doi https://doi.org/10.5281/zenodo.8118132 which always points to the latest version of your software:
> 
> ![image](https://github.com/nrc-cnrc/Canadian-Airspace-Models/assets/1444241/5ee12667-1628-4931-99dd-e068b108355b)
> 
> 

Yep! This should address your very first comment above too. For context, the use of DOI and how to cite software was something we needed to address the ASTM and RTCA DAA standards a few years ago. The concern was that tags can be changed and citing a specific commit wasn't a good practice. We liked the idea of referencing a software release and wanted something easily portable. Furthermore there was the hypothetical "what if something happens to GitHub in the future" question. Zenodo was attractive was because of it strong funding source. DOI was attractive because it offered a permanent reference while in a format that a wider audience was comfortable with; DOI isn't just for software. The ease of use of integrating Zenodo and GitHub was the last attractive piece.

In retrospective, we haven't faced any issues using Zenodo DOI in the standards or peer reviewed papers the past couple years.

**Comment by aweinert-MIT** [comment]
> I just manually corrected :) It worked! 

Yep, you can always manually edit the Zenodo record. It sometimes does import anything nicely but the CITATIOM.cff should help with this

**Comment by ftessier** [comment]
@aweinert-MIT yes I see how the Concept citation (permanent base citation) solves the issue I had years ago with EGSnrc, not wanting to cite a specific version. I will consider this again. We got an NRC-generated doi, but it has already proved to be somewhat "fragile", since NRC moved the target from the repo itself to an internal page about the software.

Do you know if it is possible to generate a badge for the base doi?

**Comment by aweinert-MIT** [comment]
> @aweinert-MIT yes I see how the Concept citation (permanent base doi) solves the issue I had years ago with EGSnrc, not wanting to cite a specific version. I will consider this again. We got an NRC-generated doi, but it has already proved to be somewhat "fragile", since NRC moved the target from the repo itself to an internal page about the software.
> 
> Do you know if it is possible to generate a badge for the base doi?

I believe you can modify the code behind the DOI badge when you copy the source from Zenodo. (I think). For the airspace encounter model repos, we always have the DOI badge point to the latest and haven't tried what you're asking.

I have had no issues with the Zenodo DOI being "fragile." This is one reason why I recommend it.
