### ISSUE TITLE
Add CITATION.cff

### ISSUE THREAD

**Issue by aweinert-MIT** [nrc-cnrc/Canadian-Airspace-Models#9]
To improve citing this repository and enabling proper attribution, please add a `CITATION.cff`. GitHub Doc has good documentation on how to do this: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by spydoctor** [comment]
Added citation file

**Comment by aweinert-MIT** [comment]
Looks good! I think you can close this issue
